#!/usr/bin/env bash

# Run spotless checks on staged files only.
# This is faster than running spotless on all files.
./mvnw spotless:check -DspotlessFiles="$(git diff --staged --name-only | grep ".java$" | sed 's/^/.*/' | paste -sd ',' -)"

declare errcode=$?
if [ $errcode -ne 0 ]; then
    echo
    echo "Run \`./mvnw spotless:apply\` to automatically fix these format violations."
    exit $errcode
fi
