name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# To cancel a currently running workflow from the same PR, branch, or tag
# when a new workflow is triggered.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: docker buildx build . --file Dockerfile --tag miguno/java-docker-build-tutorial:$(date +%s)
